# Generated by Django 4.2.1 on 2023-05-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno_taller',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('en_proceso', 'En proceso'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado'), ('ausente', 'Ausente')], default='en_proceso', max_length=10),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='papeles_en_regla',
            field=models.BooleanField(default=True),
        ),
    ]
