# Generated by Django 4.2.1 on 2023-05-14 02:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_alter_turno_taller_taller_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='cod_postal',
            field=models.CharField(default=1010, max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taller',
            name='direccion',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='taller',
            name='localidad',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='taller',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_nombre_taller', message='El nombre de taller debe tener solo numeros y letras', regex='^[a-zA-Z0-9]+$')]),
        ),
        migrations.AlterField(
            model_name='taller',
            name='provincia',
            field=models.CharField(max_length=30),
        ),
    ]
