# Generated by Django 4.2.1 on 2023-05-26 06:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_alter_turno_taller_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='frecuencia_km',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
