# Generated by Django 4.2.1 on 2023-05-26 08:15

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_service_frecuencia_km'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist_service',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('elemento', models.TextField()),
                ('tarea', models.TextField()),
                ('costo_reemplazo', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_reemplazo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='Service_tasks',
            fields=[
                ('id_id_tasks', models.AutoField(primary_key=True, serialize=False)),
                ('id_tasks', models.JSONField()),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.service')),
            ],
        ),
    ]
