# Generated by Django 4.2.1 on 2023-05-14 03:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_checklist_reparacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registro_reparacion',
            fields=[
                ('id_registro', models.AutoField(primary_key=True, serialize=False)),
                ('costo_total', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('duracion_total', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.turno_taller')),
                ('tasks', models.ManyToManyField(to='administracion.checklist_reparacion')),
            ],
        ),
    ]
