# Generated by Django 4.2.1 on 2023-05-14 03:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_registro_reparacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_reparacion',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='Registro_evaluacion_admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_total', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000000)])),
                ('duracion_total_reparaciones', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('puntaje_total', models.IntegerField(default=2500, validators=[django.core.validators.MinValueValidator(-2500), django.core.validators.MaxValueValidator(2500)])),
                ('detalle', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.turno_taller')),
            ],
        ),
    ]
