# Generated by Django 4.2.1 on 2023-05-14 07:44

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_registro_reparacion_fecha_registro_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist_evaluacion',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('elemento', models.CharField(max_length=80)),
                ('tarea', models.TextField()),
                ('costo_reemplazo', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('duracion_reemplazo', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator])),
                ('puntaje_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2500)])),
            ],
        ),
        migrations.CreateModel(
            name='Registro_evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tasks_realizadas', models.ManyToManyField(related_name='evaluacion_realizada', to='administracion.checklist_evaluacion')),
                ('id_turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.turno_taller')),
                ('puntajes_seleccionados', models.ManyToManyField(related_name='puntajes_seleccionados', to='administracion.checklist_evaluacion')),
            ],
        ),
    ]
