# Generated by Django 4.2.1 on 2023-05-14 09:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_checklist_evaluacion_registro_evaluacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro_evaluacion',
            name='id_tasks_realizadas',
        ),
        migrations.RemoveField(
            model_name='registro_evaluacion',
            name='puntajes_seleccionados',
        ),
        migrations.AddField(
            model_name='registro_evaluacion',
            name='id_task_puntaje',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Id_task_puntaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_seleccionado', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2500)])),
                ('id_task', models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='administracion.checklist_evaluacion')),
            ],
        ),
    ]
