# Generated by Django 4.2.1 on 2023-05-29 23:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_registro_extraordinario_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_reparacion',
            name='estado',
            field=models.CharField(choices=[('en_proceso', 'En proceso'), ('terminado', 'Terminado')], default='en_proceso', max_length=10),
        ),
        migrations.AlterField(
            model_name='taller',
            name='nombre',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator(code='invalid_nombre_taller', message='El nombre de taller debe contener solo números, letras, espacios y &', regex='^[a-zA-Z0-9&\\s]+$')]),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='patente',
            field=models.CharField(max_length=7, validators=[django.core.validators.RegexValidator('^(([A-Z]{2}\\d{3}[A-Z]{2})|([A-Z]{3}\\d{3}))$', code='invalid_patente', message='La patente ingresada no es valida. Debe ser en mayusculas con el formato 00AAA00 o AAA000 ')]),
        ),
    ]
