# Generated by Django 4.2.1 on 2023-05-16 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_id_task_puntaje_id_turno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_evaluacion_admin',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.turno_taller'),
        ),
    ]
