# Generated by Django 4.2.1 on 2023-05-16 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_registro_evaluacion_admin_id_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_evaluacion_admin',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.turno_taller'),
        ),
        migrations.AlterField(
            model_name='turno_taller',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('rechazado', 'Rechazado'), ('en_proceso', 'En proceso'), ('terminado', 'Terminado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=10),
        ),
    ]
