# Generated by Django 4.2.1 on 2023-05-15 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_delete_id_task_puntaje'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registro_evaluacion_admin',
            new_name='Registro_evaluacion_para_admin',
        ),
    ]
