# Generated by Django 4.2.1 on 2023-05-31 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_taller_estado_taller_id_sucursal_alter_taller_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='id_sucursal',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
