# Generated by Django 4.2.1 on 2023-05-16 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_rename_registro_evaluacion_admin_registro_evaluacion_para_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_evaluacion',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.turno_taller', unique=True),
        ),
        migrations.AlterField(
            model_name='registro_evaluacion_para_admin',
            name='id_turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='administracion.turno_taller', unique=True),
        ),
    ]
