# Generated by Django 4.2.1 on 2023-05-16 00:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_alter_registro_evaluacion_id_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_evaluacion_para_admin',
            name='id_turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='administracion.turno_taller'),
        ),
    ]
