# Generated by Django 4.2.1 on 2023-05-16 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_alter_registro_evaluacion_para_admin_id_turno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro_evaluacion_para_admin',
            name='duracion_total_reparaciones',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
