# Generated by Django 4.2.1 on 2023-05-31 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_alter_taller_id_taller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taller',
            name='estado',
        ),
    ]
