# Generated by Django 4.2.1 on 2023-05-16 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_alter_registro_evaluacion_para_admin_duracion_total_reparaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro_evaluacion',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
