# Generated by Django 4.2.1 on 2023-05-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_registro_evaluacion_detalle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_evaluacion',
            name='elemento',
            field=models.TextField(),
        ),
    ]
