# Generated by Django 4.2.1 on 2023-05-31 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_remove_taller_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
