# Generated by Django 4.2.1 on 2023-05-16 08:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_alter_checklist_evaluacion_elemento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklist_evaluacion',
            name='puntaje_max',
            field=models.IntegerField(default=2500, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2500)]),
        ),
    ]
