# Generated by Django 4.2.1 on 2023-05-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_alter_registro_evaluacion_admin_id_turno_and_more'),
        ('administracion', '0018_alter_checklist_evaluacion_puntaje_max'),
    ]

    operations = [
    ]
